### ISSUE TITLE
ChangeHost issue and solution I have found out

### ISSUE THREAD

**Issue by Ryuujimaru** [tfitz237/stardew-mp-save-editor#8] opened 2018-05-14 09:15 UTC
I try used this tool to change host to my friend which is a married farmhand. The editing save file process was done correctly, but when he try to host with the save the game will crash.

I tried to fix this problem and found out that the Host's spouse NPC must be placed in the FarmHouse, so I move his spouse NPC from his Cabin to FarmHouse then move my spouse in FarmHouse to his Cabin. 

After that he try to host again and this time has no problem.

Please take a look at this issue.

Sorry if my English is not so good. Thank you.

**Comment by tfitz237** [comment] 2018-05-14 21:55
Gotcha! Copy spouse npc from cabin to farmhouse. Will get a new release built for this ASAP

**Comment by tfitz237** [comment] 2018-05-14 22:52
Hi @Ryuujimaru I don't have a save file that has this information, so I can't test it. I created a build and put it below. Can you either test with the below build, or send me your save file so I can test? 
Thanks

Build v0.1.3.1
[Stardew.MPSaveEditor beta.zip](https://github.com/tfitz237/stardew-mp-save-editor/files/2002846/Stardew.MPSaveEditor.beta.zip)

**Comment by Ryuujimaru** [comment] 2018-05-16 02:12
Okay I'll have a test after work.thank!

**Comment by tfitz237** [comment] 2018-05-16 19:42
Looks like the real game-breaker is the NPC's DefaultMap. That makes sense! I'm working on a big release and i'll be sure to put this fix in there. Thanks so much!

**Comment by tfitz237** [comment] 2018-06-25 19:45
Fixed with FMS in v0.2.0

**Comment by eschwarz301** [comment] 2020-08-29 23:40
Confirmed fixed and still working.

**Closed by eschwarz301** 2020-08-29 23:40 UTC
Labels: bug
